- name: Install Apache2
  package:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - apache2
    - libapache2-mod-php

- name: Start service Apache2
  service:
    name: apache2
    state: started
    enabled: true

- name: Copy Apache configuration file
  template:
    src: apache2.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
  notify: restart apache
